### PR TITLE
Add option to create a tomcat system user

### PR DESCRIPTION
**Pull request by AMeng**
I would prefer to create the tomcat user as a system user. The [Ansible user command](http://docs.ansible.com/ansible/user_module.html#options) allows you to do that with the `system: yes` flag. 

This PR adds the option to the tomcat role. This is opt-in, so the default behavior is unchanged.

### CODE REVIEW

**Comment by spul** [comment]
Sorry, this got lost in a lot of work here. I'd ask to update on [2.0.0][1] or I'll integrate that in upcoming 2.1.0.

**Comment by AMeng** [comment]
No worries. Rebased against master.

**Comment by spul** [comment]
Got to this finaly. I'm testing your update right now. Everything looks good so far. I'll update `next` here soon and your patch will get to next release. Thanks for

* the very much appreciated contribution
* your patience!

# kraM

**Comment by spul** [comment]
Pushed to next after picking your commits in. Thanks! :)

**Pull request closed without merging**
