### PR TITLE
catalina_base facts and facts overriding mechanism

### PR DESCRIPTION
**Pull request by kakawait**
As discussed on #13 

Moreover I need review for the second part `catalina_base` facts.

I add `catalina_base` on facts but two questions:

1. Should be add by default? Or keep only `version`
2. By using `ini` format we can't create nested section `instance -> {{ instance.name }}`, so two solutions:
    1. Use convention like `[instance:foo]`, `[instance_foo]`, `[instance/foo]`
    2. Use json 

```
{
    "general": {"version":"{{ tomcat_version }}"},  
    "instances": {
{% for instance in tomcat_instances %}  
        "{{ instance.name }}":{"catalina_base":"{{ instance.path|default(tomcat_default_instance_path) }}/catalina/{{ instance.name }}"}{% if not loop.last %},{% endif %}
{% endfor %}
    }
}
```

that will produce something like

```json
127.0.0.1 | success >> {
    "ansible_facts": {
        "ansible_local": {
            "java": {
                "general": {
                    "java_home": "/usr/java/default"
                }
            }, 
            "tomcat": {
                "general": {
                    "version": "7.0.62"
                }, 
                "instances": {
                    "foo": {
                        "catalina_base": "/home/vagrant/catalina/foo"
                    }
                }
            }, 
            "util": {
                "init": {
                    "system": "sysvinit"
                }
            }
        }
    }, 
    "changed": false
}
```

but `json` does not allow comment, so we will loose the fabulous cow

```
#  --------------------
# ( Managed by Ansible )
#  --------------------
#   o            .    .     .
#    o      .  . .     `  ,
#     o    .; .  : .' :  :  : .
#      o   i..`: i` i.i.,i  i .
#       o   `,--.|i |i|ii|ii|i:
#            UooU\.'@@@@@@`.||'
#            \__/(@@@@@@@@@@)'
#                 (@@@@@@@@)
#                 `YY~~~~YY'
#                  ||    ||
```

### CODE REVIEW

**Comment by spul** [comment]
Hi, never worked with facts as json. Different point of views: I like the flaming sheep, but more than that I like flexible and nice roles. From that one, json wins especialy when making facts re-usable.
Next thought is more on templates in general if there are hooks on the templates changed events. Using {{ ansible_managed }} default configuration will always update templates (time/date strings, et cetera). Again json would win, as the template will not update, if fact related data was not updated.

What about making facts format configurable ``tomcat_facts_format: json`` (# ['json', 'ini']) to decide which style of facts deployment one wants to use and provide default templates based on ``tomact_facts_template: facts.{{ tomcat_facts_format }}.j2`` with default to json.

I'd add instance configuration (e.g. ports) and whether it is allowed to automatically restart tomcat to the facts template as well.

**Comment by kakawait** [comment]
I'm totally agree to add other instance configuration like ports. In other hand I don't think it could be a good idea to propose two different formats (`json` and `ini`) that produces different outputs. Indeed we cannot reproduce nested section in `ini` format, thus by changer format you will change facts structure that can be strange/inaffordant. May I was wrong, it's my point of view.

**Comment by spul** [comment]
Sounds reasonable. Let's go for json and add instance related configuration. Might be interesting to add service configuration as well (especially with systemd this might be very interesting).
I'm looking forward for an updated/complete PR based on this discussion as addition to your current work :)

**Comment by kakawait** [comment]
Do you have list of all configurations that you want to expose on facts?

**Comment by spul** [comment]
I'd go for anything interesting based on defaults/main.yml and probably anything that might be configured on a per instance basis.
There's no need right now to have everything involved completely. Just for a start to add anything, which might be interesting for other roles/tasks.

**Comment by kakawait** [comment]
Just pushed JSON format with some instances configurations.
Tested on Centos 6 sysvinit with 1 or N instances

Sample result:

```
127.0.0.1 | success >> {
    "ansible_facts": {
        "ansible_local": {
            "java": {
                "general": {
                    "java_home": "/usr/java/default"
                }
            }, 
            "tomcat": {
                "general": {
                    "allow_restart": true, 
                    "catalina_home": "/opt/tomcat/apache-tomcat-7.0.62", 
                    "version": "7.0.62"
                }, 
                "instances": {
                    "bar": {
                        "catalina_base": "/srv/tomcatbar/catalina/bar", 
                        "group": "tomcatbar", 
                        "port": {
                            "ajp": 28009, 
                            "connector": 28080, 
                            "redirect": 28443, 
                            "shutdown": 28005
                        }, 
                        "service": {
                            "file": "/etc/init.d/tomcat-bar", 
                            "name": "tomcat-bar"
                        }, 
                        "user": "tomcatbar"
                    }, 
                    "foo": {
                        "catalina_base": "/srv/tomcatfoo/catalina/foo", 
                        "group": "tomcatfoo", 
                        "port": {
                            "ajp": 18009, 
                            "connector": 18080, 
                            "redirect": 18443, 
                            "shutdown": 18005
                        }, 
                        "service": {
                            "file": "/etc/init.d/tomcat-foo", 
                            "name": "tomcat-foo"
                        }, 
                        "user": "tomcatfoo"
                    }
                }
            }, 
            "util": {
                "init": {
                    "system": "sysvinit"
                }
            }
        }
    }, 
    "changed": false
}
```

**Comment by kakawait** [comment]
And with basic role usage

```yml
---
- hosts: tomcat_server
  roles:
    - { role: ansible-tomcat }
```

```json
127.0.0.1 | success >> {
    "ansible_facts": {
        "ansible_local": {
            "java": {
                "general": {
                    "java_home": "/usr/java/default"
                }
            }, 
            "tomcat": {
                "general": {
                    "allow_restart": true, 
                    "catalina_home": "/opt/tomcat/apache-tomcat-7.0.62", 
                    "version": "7.0.62"
                }, 
                "instances": {
                    "tomcat": {
                        "catalina_base": "/srv/tomcat/catalina/tomcat", 
                        "group": "tomcat", 
                        "port": {
                            "ajp": 8009, 
                            "connector": 8080, 
                            "redirect": 8443, 
                            "shutdown": 8005
                        }, 
                        "service": {
                            "file": "/etc/init.d/tomcat", 
                            "name": "tomcat"
                        }, 
                        "user": "tomcat"
                    }
                }
            }, 
            "util": {
                "init": {
                    "system": "sysvinit"
                }
            }
        }
    }, 
    "changed": false
}
```

**Comment by kakawait** [comment]
(Yes I flood :)) But should we keep to possibility to customize `facts.j2` template?

**Comment by spul** [comment]
Yes, I think we should keep that possibility. Testing on the update with different configurations right now.

**Comment by spul** [comment]
Picked into mainline. I'll go for [issues/12](https://github.com/silpion/ansible-tomcat/issues/12) and provide a release including #16 and #17.

**Comment by spul** [comment]
Integrated with [1.1.0](https://github.com/silpion/ansible-tomcat/tree/1.1.0) and released to galaxy. Thank you for your efforts!

**Pull request closed without merging**
